<?php
require_once 'includes/auth.php';
require_once 'includes/game_functions.php';

// Require login
$auth->requireLogin();
$user = $auth->getCurrentUser();

// Get user preferences and available backgrounds
$userPrefs = getUserPreferences($user['id']);
$backgrounds = getAvailableBackgrounds();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sliding Puzzle Game</title>
    <link rel="stylesheet" href="css/game.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>
<body>
    <div class="game-container">
        <!-- Header -->
        <header class="game-header">
            <div class="header-left">
                <h1><i class="fas fa-puzzle-piece"></i> Sliding Puzzle</h1>
            </div>
            <div class="header-right">
                <span class="welcome">Welcome, <?php echo htmlspecialchars($user['username']); ?>!</span>
                <?php if ($user['is_admin']): ?>
                    <a href="admin.php" class="btn btn-admin"><i class="fas fa-cog"></i> Admin</a>
                <?php endif; ?>
                <a href="logout.php" class="btn btn-logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </header>

        <div class="game-content">
            <!-- Game Info Panel -->
            <div class="info-panel">
                <div class="game-stats">
                    <div class="stat-item">
                        <i class="fas fa-mouse-pointer"></i>
                        <span>Moves: <span id="move-count">0</span></span>
                    </div>
                    <div class="stat-item">
                        <i class="fas fa-clock"></i>
                        <span>Time: <span id="timer">00:00</span></span>
                    </div>
                </div>
                
                <div class="game-controls">
                    <button id="shuffle-btn" class="btn btn-primary">
                        <i class="fas fa-random"></i> Shuffle
                    </button>
                    <button id="new-game-btn" class="btn btn-secondary">
                        <i class="fas fa-redo"></i> New Game
                    </button>
                </div>

                <!-- Background Selection -->
                <div class="background-selector">
                    <label for="background-select">
                        <i class="fas fa-image"></i> Background:
                    </label>
                    <select id="background-select">
                        <?php foreach ($backgrounds as $bg): ?>
                            <option value="<?php echo htmlspecialchars($bg['filename']); ?>" 
                                    <?php echo ($bg['filename'] === $userPrefs['preferred_background']) ? 'selected' : ''; ?>>
                                <?php echo htmlspecialchars($bg['display_name']); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <!-- Game Board -->
            <div class="game-board-container">
                <div id="puzzle-board" class="puzzle-board">
                    <!-- Tiles will be generated by JavaScript -->
                </div>
                
                <!-- Game Status -->
                <div id="game-status" class="game-status">
                    <p>Click "Shuffle" to start a new game!</p>
                </div>
            </div>

            <!-- Leaderboard -->
            <div class="leaderboard-panel">
                <h3><i class="fas fa-trophy"></i> Leaderboard</h3>
                <div id="leaderboard" class="leaderboard">
                    <!-- Leaderboard will be loaded by JavaScript -->
                </div>
                <button id="view-history-btn" class="btn btn-outline">
                    <i class="fas fa-history"></i> My History
                </button>
            </div>
        </div>
    </div>

    <!-- Win Modal -->
    <div id="win-modal" class="modal-overlay" style="display: none;">
        <div class="modal-content">
            <div class="modal-header">
                <h2><i class="fas fa-trophy"></i> Congratulations!</h2>
            </div>
            <div class="modal-body">
                <p>You solved the puzzle!</p>
                <div class="final-stats">
                    <div class="final-stat">
                        <i class="fas fa-clock"></i>
                        <span>Time: <span id="final-time"></span></span>
                    </div>
                    <div class="final-stat">
                        <i class="fas fa-mouse-pointer"></i>
                        <span>Moves: <span id="final-moves"></span></span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="play-again-btn" class="btn btn-primary">
                    <i class="fas fa-redo"></i> Play Again
                </button>
                <button id="close-modal-btn" class="btn btn-secondary">
                    <i class="fas fa-times"></i> Close
                </button>
            </div>
        </div>
    </div>

    <!-- User History Modal -->
    <div id="history-modal" class="modal-overlay" style="display: none;">
        <div class="modal-content">
            <div class="modal-header">
                <h2><i class="fas fa-history"></i> Your Game History</h2>
                <button class="close-btn" onclick="closeHistoryModal()">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="modal-body">
                <div id="user-history" class="user-history">
                    <!-- History will be loaded by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <!-- W3C Validator Links -->
    <div class="w3c-links">
        <a href="https://validator.w3.org/check/referer">
            <img src="https://www.w3.org/Icons/valid-xhtml11" alt="Valid XHTML 1.1" />
        </a>
        <a href="https://jigsaw.w3.org/css-validator/check/referer">
            <img src="https://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS" />
        </a>
    </div>

    <script>
        // Pass PHP data to JavaScript
        window.gameData = {
            userId: <?php echo $user['id']; ?>,
            username: '<?php echo htmlspecialchars($user['username']); ?>',
            currentBackground: '<?php echo htmlspecialchars($userPrefs['preferred_background']); ?>'
        };
    </script>
    <script src="js/game.js"></script>
</body>
</html>
